### ISSUE TITLE
Cannot use namespace 'TdWebConfig'/'TdWebClient' as a type

### ISSUE THREAD

**Issue by sh-a-v** [airgram/tdweb-airgram#1]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**`tdweb-irgram` version:**

[ ] `latest`
[ ] `@next`
[x] `1.1.1`

**Steps to reproduce or a small repository showing the problem:**

![s113](https://user-images.githubusercontent.com/7159528/60399379-45b87300-9b6c-11e9-80d6-ff32edc0f6da.png)

There is no error if I copy the file `tdweb.d.ts` to my project.

**Comment by airgram** [comment]
You can import typings before `tdweb-airgram`:
```
import 'tdweb-airgram/tdweb'
import { ag, Airgram } from 'tdweb-airgram'
```

**Comment by sh-a-v** [comment]
Hmm

![s115](https://user-images.githubusercontent.com/7159528/60454261-0e18fc00-9c3c-11e9-927c-88d319d3755b.png)

**Comment by airgram** [comment]
Check if you installed `rollup-plugin-node-resolve` and `rollup-plugin-commonjs` plugins in your rollup config like in [this example](https://github.com/airgram/tdweb-airgram/blob/master/examples/rollup-example/rollup.config.ts#L25-L26).

**Comment by sh-a-v** [comment]
I checked the repository example and got the same:

![s116](https://user-images.githubusercontent.com/7159528/60619313-0fcff480-9de1-11e9-907d-134be2242cb3.png)

https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency

**Comment by sh-a-v** [comment]
Maybe there is no bug, types are not needed in the bundle..

**Comment by airgram** [comment]
Without any declaration you will receive the error: `Could not find a declaration file for module 'tdweb'.`

At the moment, the most reliable solution is to copy the `tdweb.d.ts` file in your project, as you mentioned above.

**Comment by esindger** [comment]
Now you can use [@types/tdweb](https://www.npmjs.com/package/@types/tdweb) package.

**Comment by sh-a-v** [comment]
Thanks!
