### ISSUE TITLE
'TDLibError' is not exported

### ISSUE THREAD

**Issue by sh-a-v** [airgram/tdweb-airgram#2]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**`tdweb-irgram` version:**

[ ] `latest`
[ ] `@next`
[x] `1.1.1`

**Steps to reproduce or a small repository showing the problem:**

![s114](https://user-images.githubusercontent.com/7159528/60399441-03436600-9b6d-11e9-90e2-1c94c59923b2.png)

**Comment by airgram** [comment]
Please can you provide your rollup config?

**Comment by sh-a-v** [comment]
I use [stenciljs](https://github.com/ionic-team/stencil). It may be necessary to add `module` to `package.json` (https://github.com/rollup/rollup/wiki/pkg.module)?

**Comment by airgram** [comment]
Unfortunately, I did not work with `stencil`, but I can prepare `rollup` starter example.

**Comment by airgram** [comment]
Please check out version `1.1.4`

**Comment by sh-a-v** [comment]
It works properly now. Thanks.
